In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Dataset-Mental-Disorders.csv')
df.head()

Patient Number    Sadness    Euphoric  Exhausted Sleep dissorder Mood Swing  \
0     Patiant-01    Usually      Seldom  Sometimes       Sometimes        YES   
1     Patiant-02    Usually      Seldom    Usually       Sometimes         NO   
2     Patiant-03  Sometimes  Most-Often  Sometimes       Sometimes        YES   
3     Patiant-04    Usually      Seldom    Usually      Most-Often        YES   
4     Patiant-05    Usually     Usually  Sometimes       Sometimes         NO   

  Suicidal thoughts Anorxia Authority Respect Try-Explanation  \
0              YES       NO                NO             YES   
1               YES      NO                NO              NO   
2                NO      NO                NO             YES   
3               YES     YES                NO             YES   
4                NO      NO                NO              NO   

  Aggressive Response Ignore & Move-On Nervous Break-down Admit Mistakes  \
0                  NO               NO                YES            YES   
1                  NO               NO                 NO             NO   
2                 YES               NO                YES            YES   
3                  NO               NO                 NO             NO   
4                  NO               NO                YES            YES   

  Overthinking Sexual Activity Concentration  Optimisim Expert Diagnose  
0          YES       3 From 10     3 From 10  4 From 10  Bipolar Type-2  
1           NO       4 From 10     2 From 10  5 From 10      Depression  
2           NO       6 From 10     5 From 10  7 From 10  Bipolar Type-1  
3           NO       3 From 10     2 From 10  2 From 10  Bipolar Type-2  
4          YES       5 From 10     5 From 10  6 From 10          Normal

In [3]:
print(df.columns)
print(len(df.columns))

Index(['Patient Number', 'Sadness', 'Euphoric', 'Exhausted', 'Sleep dissorder',
       'Mood Swing', 'Suicidal thoughts', 'Anorxia', 'Authority Respect',
       'Try-Explanation', 'Aggressive Response', 'Ignore & Move-On',
       'Nervous Break-down', 'Admit Mistakes', 'Overthinking',
       'Sexual Activity', 'Concentration', 'Optimisim', 'Expert Diagnose'],
      dtype='object')
19


In [4]:
def trans_cl_name():
    translation = {
        "Patient Number": "病人編號",
        "Sadness": "悲傷",
        "Euphoric": "狂喜",
        "Exhausted": "筋疲力盡",
        "Sleep dissorder": "睡眠障礙",
        "Mood Swing": "情緒波動",
        "Suicidal thoughts": "自殺念頭",
        "Anorxia": "厭食症",
        "Authority Respect": "尊重權威",
        "Try-Explanation": "嘗試解釋",
        "Aggressive Response": "積極回應",
        "Ignore & Move-On": "忽略並繼續前進",
        "Nervous Break-down": "神經崩潰",
        "Admit Mistakes": "承認錯誤",
        "Overthinking": "過度思考",
        "Sexual Activity": "性行為",
        "Concentration": "注意力",
        "Optimisim": "樂觀主義",
        "Expert Diagnose": "專家診斷"
    }
    # 轉成中文
    df.rename(columns=translation, inplace=True)
    df.head()

In [5]:
a=df['Expert Diagnose'].value_counts()
item_counts = pd.Series(a)
# 使用 index 屬性取得項目的名稱
item_names = item_counts.index.tolist()
print(item_names)

['Bipolar Type-2', 'Depression', 'Normal', 'Bipolar Type-1']


In [6]:
# 資料清洗 先刪除病人編號
df = df.drop(columns=['Patient Number'])
cols=list(df.columns)

In [7]:
# 檢驗有無遺漏直
for col in cols:
    missing_values=df[col].isnull().sum()
    print(f'{col}項目的缺失值為: {missing_values}')

Sadness項目的缺失值為: 0
Euphoric項目的缺失值為: 0
Exhausted項目的缺失值為: 0
Sleep dissorder項目的缺失值為: 0
Mood Swing項目的缺失值為: 0
Suicidal thoughts項目的缺失值為: 0
Anorxia項目的缺失值為: 0
Authority Respect項目的缺失值為: 0
Try-Explanation項目的缺失值為: 0
Aggressive Response項目的缺失值為: 0
Ignore & Move-On項目的缺失值為: 0
Nervous Break-down項目的缺失值為: 0
Admit Mistakes項目的缺失值為: 0
Overthinking項目的缺失值為: 0
Sexual Activity項目的缺失值為: 0
Concentration項目的缺失值為: 0
Optimisim項目的缺失值為: 0
Expert Diagnose項目的缺失值為: 0


In [8]:
# 逐個項目替換 先進行檢驗
for col in cols:
    print(df[col].unique())

['Usually' 'Sometimes' 'Seldom' 'Most-Often']
['Seldom' 'Most-Often' 'Usually' 'Sometimes']
['Sometimes' 'Usually' 'Seldom' 'Most-Often']
['Sometimes' 'Most-Often' 'Usually' 'Seldom']
['YES' 'NO']
['YES ' 'YES' 'NO']
['NO' 'YES']
['NO' 'YES']
['YES' 'NO']
['NO' 'YES']
['NO' 'YES']
['YES' 'NO']
['YES' 'NO']
['YES' 'NO']
['3 From 10' '4 From 10' '6 From 10' '5 From 10' '7 From 10' '8 From 10'
 '9 From 10' '2 From 10' '1 From 10']
['3 From 10' '2 From 10' '5 From 10' '4 From 10' '7 From 10' '6 From 10'
 '1 From 10' '8 From 10']
['4 From 10' '5 From 10' '7 From 10' '2 From 10' '6 From 10' '9 From 10'
 '3 From 10' '8 From 10' '1 From 10']
['Bipolar Type-2' 'Depression' 'Bipolar Type-1' 'Normal']


In [9]:
temp={}
for i in range(1,11):
    temp[str(str(i)+' From 10')]=int(i)
print(temp)

{'1 From 10': 1, '2 From 10': 2, '3 From 10': 3, '4 From 10': 4, '5 From 10': 5, '6 From 10': 6, '7 From 10': 7, '8 From 10': 8, '9 From 10': 9, '10 From 10': 10}


In [10]:
wash={
'1 From 10': 1, '2 From 10': 2, '3 From 10': 3, '4 From 10': 4, 
'5 From 10': 5, '6 From 10': 6, '7 From 10': 7, '8 From 10': 8, 
'9 From 10': 9, '10 From 10': 10,
'NO':0, 'YES':1,'YES ':1,
'Usually':3, 'Sometimes':2, 
'Seldom':1, 'Most-Often':4,
'Bipolar Type-2':2, 'Depression':3, 
'Bipolar Type-1':1, 'Normal':0,
}

In [11]:
for column in df.columns:
    df[column]= df[column].replace(wash)
# 必須特別處理Suicidal thoughts的 0 因為它資料有誤
df.head()

C:\Users\william\AppData\Local\Temp\ipykernel_17744\1308317911.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column]= df[column].replace(wash)


Sadness  Euphoric  Exhausted  Sleep dissorder  Mood Swing  \
0        3         1          2                2           1   
1        3         1          3                2           0   
2        2         4          2                2           1   
3        3         1          3                4           1   
4        3         3          2                2           0   

   Suicidal thoughts  Anorxia  Authority Respect  Try-Explanation  \
0                  1        0                  0                1   
1                  1        0                  0                0   
2                  0        0                  0                1   
3                  1        1                  0                1   
4                  0        0                  0                0   

   Aggressive Response  Ignore & Move-On  Nervous Break-down  Admit Mistakes  \
0                    0                 0                   1               1   
1                    0                 0                   0               0   
2                    1                 0                   1               1   
3                    0                 0                   0               0   
4                    0                 0                   1               1   

   Overthinking  Sexual Activity  Concentration  Optimisim  Expert Diagnose  
0             1                3              3          4                2  
1             0                4              2          5                3  
2             0                6              5          7                1  
3             0                3              2          2                2  
4             1                5              5          6                0

In [12]:
for i in df.columns:
    print(df.loc[:,i].unique())

[3 2 1 4]
[1 4 3 2]
[2 3 1 4]
[2 4 3 1]
[1 0]
[1 0]
[0 1]
[0 1]
[1 0]
[0 1]
[0 1]
[1 0]
[1 0]
[1 0]
[3 4 6 5 7 8 9 2 1]
[3 2 5 4 7 6 1 8]
[4 5 7 2 6 9 3 8 1]
[2 3 1 0]


In [13]:
new_file_name = 'new_md.csv'
df.to_csv(new_file_name, index=False)
print('保存成功')

保存成功
